const EMOJI_LIST = [
  { name: "smile", emoji: "😄", description: "happy joy grin" },
  { name: "smiley", emoji: "😃", description: "happy joy grin" },
  { name: "grinning", emoji: "😀", description: "happy joy" },
  { name: "grin", emoji: "😁", description: "happy teeth" },
  { name: "joy", emoji: "😂", description: "tears laugh" },
  { name: "laughing", emoji: "😆", description: "lol happy" },
  { name: "sweat_smile", emoji: "😅", description: "relief nervous" },
  { name: "rofl", emoji: "🤣", description: "rolling floor laugh" },
  { name: "wink", emoji: "😉", description: "flirt" },
  { name: "blush", emoji: "😊", description: "proud shy" },
  { name: "relaxed", emoji: "☺️", description: "smile calm" },
  { name: "heart_eyes", emoji: "😍", description: "love" },
  { name: "kissing", emoji: "😗", description: "kiss" },
  { name: "thinking", emoji: "🤔", description: "hmm" },
  { name: "neutral_face", emoji: "😐", description: "meh" },
  { name: "expressionless", emoji: "😑", description: "meh" },
  { name: "unamused", emoji: "😒", description: "annoyed" },
  { name: "rolling_eyes", emoji: "🙄", description: "eyeroll" },
  { name: "grimacing", emoji: "😬", description: "awkward" },
  { name: "sweat", emoji: "😓", description: "nervous" },
  { name: "cry", emoji: "😢", description: "sad tear" },
  { name: "sob", emoji: "😭", description: "sad cry" },
  { name: "angry", emoji: "😠", description: "mad" },
  { name: "rage", emoji: "😡", description: "mad angry" },
  { name: "scream", emoji: "😱", description: "shock" },
  { name: "thumbsup", emoji: "👍", description: "approve ok" },
  { name: "thumbsdown", emoji: "👎", description: "disapprove" },
  { name: "clap", emoji: "👏", description: "applause" },
  { name: "wave", emoji: "👋", description: "hello" },
  { name: "muscle", emoji: "💪", description: "strong" },
  { name: "heart", emoji: "❤️", description: "love" },
  { name: "fire", emoji: "🔥", description: "lit" },
  { name: "tada", emoji: "🎉", description: "party" },
  { name: "rocket", emoji: "🚀", description: "ship" },
  { name: "eyes", emoji: "👀", description: "look" },
  { name: "pray", emoji: "🙏", description: "thanks" },
  { name: "ok_hand", emoji: "👌", description: "ok" },
  { name: "shrug", emoji: "🤷", description: "idk" },
  { name: "shrug_m", emoji: "🤷‍♂️", description: "idk man" },
  { name: "shrug_w", emoji: "🤷‍♀️", description: "idk woman" },
  { name: "warning", emoji: "⚠️", description: "caution" },
  { name: "check", emoji: "✅", description: "checkmark" },
  { name: "x", emoji: "❌", description: "cross" },
  { name: "slightly_smiling_face", emoji: "🙂", description: "smile friendly" },
  { name: "upside_down_face", emoji: "🙃", description: "silly" },
  { name: "smirk", emoji: "😏", description: "smug" },
  { name: "relieved", emoji: "😌", description: "relief" },
  { name: "yum", emoji: "😋", description: "delicious" },
  { name: "stuck_out_tongue", emoji: "😛", description: "tongue" },
  { name: "stuck_out_tongue_winking_eye", emoji: "😜", description: "wink tongue" },
  { name: "stuck_out_tongue_closed_eyes", emoji: "😝", description: "tongue" },
  { name: "hugging_face", emoji: "🤗", description: "hug" },
  { name: "sunglasses", emoji: "😎", description: "cool" },
  { name: "sleeping", emoji: "😴", description: "sleep" },
  { name: "zzz", emoji: "💤", description: "sleep" },
  { name: "mask", emoji: "😷", description: "sick" },
  { name: "thermometer_face", emoji: "🤒", description: "sick" },
  { name: "nauseated_face", emoji: "🤢", description: "sick" },
  { name: "vomiting_face", emoji: "🤮", description: "sick" },
  { name: "sneezing_face", emoji: "🤧", description: "sneeze" },
  { name: "dizzy_face", emoji: "😵", description: "dizzy" },
  { name: "confused", emoji: "😕", description: "confused" },
  { name: "worried", emoji: "😟", description: "worried" },
  { name: "frowning", emoji: "😦", description: "sad" },
  { name: "persevere", emoji: "😣", description: "struggle" },
  { name: "disappointed", emoji: "😞", description: "sad" },
  { name: "pensive", emoji: "😔", description: "sad" },
  { name: "confounded", emoji: "😖", description: "confounded" },
  { name: "tired_face", emoji: "😫", description: "tired" },
  { name: "weary", emoji: "😩", description: "weary" },
  { name: "triumph", emoji: "😤", description: "triumph" },
  { name: "poop", emoji: "💩", description: "poop" },
  { name: "skull", emoji: "💀", description: "dead" },
  { name: "ghost", emoji: "👻", description: "boo" },
  { name: "alien", emoji: "👽", description: "alien" },
  { name: "robot", emoji: "🤖", description: "robot" },
  { name: "smiley_cat", emoji: "😺", description: "cat happy" },
  { name: "heart_eyes_cat", emoji: "😻", description: "cat love" },
  { name: "crying_cat_face", emoji: "😿", description: "cat sad" },
  { name: "see_no_evil", emoji: "🙈", description: "monkey" },
  { name: "hear_no_evil", emoji: "🙉", description: "monkey" },
  { name: "speak_no_evil", emoji: "🙊", description: "monkey" },
  { name: "raised_hands", emoji: "🙌", description: "hooray" },
  { name: "handshake", emoji: "🤝", description: "deal" },
  { name: "v", emoji: "✌️", description: "peace" },
  { name: "metal", emoji: "🤘", description: "rock" },
  { name: "call_me_hand", emoji: "🤙", description: "call" },
  { name: "fist", emoji: "✊", description: "fist" },
  { name: "punch", emoji: "👊", description: "punch" },
  { name: "raised_fist", emoji: "✊", description: "solidarity" },
  { name: "point_up", emoji: "☝️", description: "point up" },
  { name: "point_down", emoji: "👇", description: "point down" },
  { name: "point_left", emoji: "👈", description: "point left" },
  { name: "point_right", emoji: "👉", description: "point right" },
  { name: "ok", emoji: "🆗", description: "ok" },
  { name: "100", emoji: "💯", description: "100" },
  { name: "sparkles", emoji: "✨", description: "sparkles" },
  { name: "star", emoji: "⭐", description: "star" },
  { name: "star2", emoji: "🌟", description: "star" },
  { name: "sunny", emoji: "☀️", description: "sun" },
  { name: "cloud", emoji: "☁️", description: "cloud" },
  { name: "umbrella", emoji: "☂️", description: "umbrella" },
  { name: "snowflake", emoji: "❄️", description: "snow" },
  { name: "zap", emoji: "⚡", description: "lightning" },
  { name: "cyclone", emoji: "🌀", description: "cyclone" },
  { name: "rainbow", emoji: "🌈", description: "rainbow" },
  { name: "moon", emoji: "🌙", description: "moon" },
  { name: "new_moon", emoji: "🌑", description: "moon" },
  { name: "full_moon", emoji: "🌕", description: "moon" },
  { name: "dog", emoji: "🐶", description: "dog" },
  { name: "cat", emoji: "🐱", description: "cat" },
  { name: "mouse", emoji: "🐭", description: "mouse" },
  { name: "hamster", emoji: "🐹", description: "hamster" },
  { name: "rabbit", emoji: "🐰", description: "rabbit" },
  { name: "bear", emoji: "🐻", description: "bear" },
  { name: "panda_face", emoji: "🐼", description: "panda" },
  { name: "koala", emoji: "🐨", description: "koala" },
  { name: "tiger", emoji: "🐯", description: "tiger" },
  { name: "lion", emoji: "🦁", description: "lion" },
  { name: "cow", emoji: "🐮", description: "cow" },
  { name: "pig", emoji: "🐷", description: "pig" },
  { name: "monkey_face", emoji: "🐵", description: "monkey" },
  { name: "chicken", emoji: "🐔", description: "chicken" },
  { name: "penguin", emoji: "🐧", description: "penguin" },
  { name: "bird", emoji: "🐦", description: "bird" },
  { name: "baby_chick", emoji: "🐤", description: "chick" },
  { name: "frog", emoji: "🐸", description: "frog" },
  { name: "octopus", emoji: "🐙", description: "octopus" },
  { name: "fish", emoji: "🐟", description: "fish" },
  { name: "turtle", emoji: "🐢", description: "turtle" },
  { name: "snake", emoji: "🐍", description: "snake" },
  { name: "bug", emoji: "🐛", description: "bug" },
  { name: "butterfly", emoji: "🦋", description: "butterfly" },
  { name: "rose", emoji: "🌹", description: "rose" },
  { name: "tulip", emoji: "🌷", description: "tulip" },
  { name: "cherry_blossom", emoji: "🌸", description: "cherry blossom" },
  { name: "seedling", emoji: "🌱", description: "plant" },
  { name: "cactus", emoji: "🌵", description: "cactus" },
  { name: "evergreen_tree", emoji: "🌲", description: "tree" },
  { name: "palm_tree", emoji: "🌴", description: "palm" },
  { name: "birthday", emoji: "🎂", description: "birthday" },
  { name: "cake", emoji: "🍰", description: "cake" },
  { name: "cookie", emoji: "🍪", description: "cookie" },
  { name: "doughnut", emoji: "🍩", description: "donut" },
  { name: "icecream", emoji: "🍦", description: "ice cream" },
  { name: "shaved_ice", emoji: "🍧", description: "ice" },
  { name: "candy", emoji: "🍬", description: "candy" },
  { name: "lollipop", emoji: "🍭", description: "lollipop" },
  { name: "coffee", emoji: "☕", description: "coffee" },
  { name: "tea", emoji: "🍵", description: "tea" },
  { name: "beer", emoji: "🍺", description: "beer" },
  { name: "beers", emoji: "🍻", description: "cheers" },
  { name: "wine_glass", emoji: "🍷", description: "wine" },
  { name: "cocktail", emoji: "🍸", description: "cocktail" },
  { name: "pizza", emoji: "🍕", description: "pizza" },
  { name: "hamburger", emoji: "🍔", description: "burger" },
  { name: "fries", emoji: "🍟", description: "fries" },
  { name: "taco", emoji: "🌮", description: "taco" },
  { name: "burrito", emoji: "🌯", description: "burrito" },
  { name: "sushi", emoji: "🍣", description: "sushi" },
  { name: "ramen", emoji: "🍜", description: "ramen" },
  { name: "spaghetti", emoji: "🍝", description: "pasta" },
  { name: "soccer", emoji: "⚽", description: "soccer" },
  { name: "basketball", emoji: "🏀", description: "basketball" },
  { name: "football", emoji: "🏈", description: "football" },
  { name: "baseball", emoji: "⚾", description: "baseball" },
  { name: "tennis", emoji: "🎾", description: "tennis" },
  { name: "trophy", emoji: "🏆", description: "trophy" },
  { name: "medal", emoji: "🏅", description: "medal" },
  { name: "musical_note", emoji: "🎵", description: "music" },
  { name: "notes", emoji: "🎶", description: "music" },
  { name: "microphone", emoji: "🎤", description: "microphone" },
  { name: "guitar", emoji: "🎸", description: "guitar" },
  { name: "game_die", emoji: "🎲", description: "game" },
  { name: "ticket", emoji: "🎫", description: "ticket" },
  { name: "gift", emoji: "🎁", description: "gift" },
  { name: "balloon", emoji: "🎈", description: "balloon" },
  { name: "confetti_ball", emoji: "🎊", description: "confetti" },
  { name: "camera", emoji: "📷", description: "camera" },
  { name: "phone", emoji: "📱", description: "phone" },
  { name: "computer", emoji: "💻", description: "computer" },
  { name: "bulb", emoji: "💡", description: "idea" },
  { name: "moneybag", emoji: "💰", description: "money" },
  { name: "gem", emoji: "💎", description: "gem" },
  { name: "key", emoji: "🔑", description: "key" },
  { name: "lock", emoji: "🔒", description: "lock" },
  { name: "unlock", emoji: "🔓", description: "unlock" },
  { name: "hourglass", emoji: "⌛", description: "time" },
  { name: "alarm_clock", emoji: "⏰", description: "alarm" },
  { name: "calendar", emoji: "📅", description: "calendar" },
  { name: "clipboard", emoji: "📋", description: "clipboard" },
  { name: "memo", emoji: "📝", description: "memo" },
  { name: "mailbox", emoji: "📫", description: "mail" },
  { name: "paperclip", emoji: "📎", description: "paperclip" },
  { name: "magnifying_glass", emoji: "🔍", description: "search" },
  { name: "exclamation", emoji: "❗", description: "exclamation" },
  { name: "question", emoji: "❓", description: "question" },
  { name: "grey_question", emoji: "❔", description: "question" },
  { name: "bangbang", emoji: "‼️", description: "bang" },
  { name: "interrobang", emoji: "⁉️", description: "interrobang" },
  { name: "speech_balloon", emoji: "💬", description: "speech" },
  { name: "thought_balloon", emoji: "💭", description: "thought" },
  { name: "car", emoji: "🚗", description: "car" },
  { name: "taxi", emoji: "🚕", description: "taxi" },
  { name: "bus", emoji: "🚌", description: "bus" },
  { name: "police_car", emoji: "🚓", description: "police" },
  { name: "ambulance", emoji: "🚑", description: "ambulance" },
  { name: "fire_engine", emoji: "🚒", description: "fire" },
  { name: "airplane", emoji: "✈️", description: "airplane" },
  { name: "train", emoji: "🚆", description: "train" },
  { name: "ship", emoji: "🚢", description: "ship" },
  { name: "bike", emoji: "🚲", description: "bike" },
  { name: "construction", emoji: "🚧", description: "construction" },
  { name: "hospital", emoji: "🏥", description: "hospital" },
  { name: "school", emoji: "🏫", description: "school" },
  { name: "office", emoji: "🏢", description: "office" },
  { name: "house", emoji: "🏠", description: "house" },
  { name: "building", emoji: "🏛️", description: "building" },
  { name: "flag_us", emoji: "🇺🇸", description: "usa" },
  { name: "flag_gb", emoji: "🇬🇧", description: "uk" }
]

export default EMOJI_LIST.map((entry) => ({
  name: entry.name,
  value: entry.name,
  emoji: entry.emoji,
  description: entry.description,
  label: `:${entry.name}:`
}))
