const EMOJI_LIST = [
  { name: "smile", emoji: "😄", description: "happy joy grin" },
  { name: "smiley", emoji: "😃", description: "happy joy grin" },
  { name: "grinning", emoji: "😀", description: "happy joy" },
  { name: "grin", emoji: "😁", description: "happy teeth" },
  { name: "joy", emoji: "😂", description: "tears laugh" },
  { name: "laughing", emoji: "😆", description: "lol happy" },
  { name: "sweat_smile", emoji: "😅", description: "relief nervous" },
  { name: "rofl", emoji: "🤣", description: "rolling floor laugh" },
  { name: "wink", emoji: "😉", description: "flirt" },
  { name: "blush", emoji: "😊", description: "proud shy" },
  { name: "relaxed", emoji: "☺️", description: "smile calm" },
  { name: "heart_eyes", emoji: "😍", description: "love" },
  { name: "kissing", emoji: "😗", description: "kiss" },
  { name: "thinking", emoji: "🤔", description: "hmm" },
  { name: "neutral_face", emoji: "😐", description: "meh" },
  { name: "expressionless", emoji: "😑", description: "meh" },
  { name: "unamused", emoji: "😒", description: "annoyed" },
  { name: "rolling_eyes", emoji: "🙄", description: "eyeroll" },
  { name: "grimacing", emoji: "😬", description: "awkward" },
  { name: "sweat", emoji: "😓", description: "nervous" },
  { name: "cry", emoji: "😢", description: "sad tear" },
  { name: "sob", emoji: "😭", description: "sad cry" },
  { name: "angry", emoji: "😠", description: "mad" },
  { name: "rage", emoji: "😡", description: "mad angry" },
  { name: "scream", emoji: "😱", description: "shock" },
  { name: "thumbsup", emoji: "👍", description: "approve ok" },
  { name: "thumbsdown", emoji: "👎", description: "disapprove" },
  { name: "clap", emoji: "👏", description: "applause" },
  { name: "wave", emoji: "👋", description: "hello" },
  { name: "muscle", emoji: "💪", description: "strong" },
  { name: "heart", emoji: "❤️", description: "love" },
  { name: "fire", emoji: "🔥", description: "lit" },
  { name: "tada", emoji: "🎉", description: "party" },
  { name: "rocket", emoji: "🚀", description: "ship" },
  { name: "eyes", emoji: "👀", description: "look" },
  { name: "pray", emoji: "🙏", description: "thanks" },
  { name: "ok_hand", emoji: "👌", description: "ok" },
  { name: "shrug", emoji: "🤷", description: "idk" },
  { name: "shrug_m", emoji: "🤷‍♂️", description: "idk man" },
  { name: "shrug_w", emoji: "🤷‍♀️", description: "idk woman" },
  { name: "warning", emoji: "⚠️", description: "caution" },
  { name: "check", emoji: "✅", description: "checkmark" },
  { name: "x", emoji: "❌", description: "cross" }
]

export default EMOJI_LIST.map((entry) => ({
  name: entry.name,
  value: entry.name,
  emoji: entry.emoji,
  description: entry.description,
  label: `:${entry.name}:`
}))
